### ISSUE TITLE
Space after string is required

### ISSUE THREAD

**Issue by blais** [jcornaz/beancount-parser#68]
In your parser, after a string, if a space is not inserted, this returns a syntax error:
```
2019-05-25 * "DELLAPIETRASGOURMET BROOKLYN            NY" "73011009146 DELLAPIETRASMEATS@GMA"#family 
```

It's not super important,  but my file contained a bunch of these (accidentally), but the Beancount C parser handles that.

**Comment by jcornaz** [comment]
Thanks for the report. This is fixed in [2.0.4](https://github.com/jcornaz/beancount-parser/releases/tag/v2.0.4)
