### ISSUE TITLE
Feature Request: Support for name_* Options

### ISSUE THREAD

**Issue by Bergschrat1** [jcornaz/beancount-parser#75]
**Description**
Currently, the library does not support the name_* options from Beancount, such as name_assets. These options allow users to customize the names of account types.
Beancount implementation: https://github.com/beancount/beancount/blob/d2d1e536c82281933b7bfc9cf3137f3698dcf4dc/beancount/parser/options.py#L245
https://beancount.github.io/docs/beancount_options_reference.html

**Proposed Solution**
To support the name_* options, the parsing logic in the library needs to be updated to dynamically handle the account types based on the options provided in the BeancountFile struct. Defaults should stay Expenses, Assets, Liabilities etc.

**Example**
```
option "name_assets" "Aktiva"
2024-03-29 balance Aktiva:Bank:Giro  123.45 USD
```

**Comment by jcornaz** [comment]
Thanks for the suggestion.

To solve this, I think the simplest solution is to be less strict about the account name format by not requiring the first component to be one of `Assets`, `Liabilities`, `Equity`, `Income` or `Expenses`.

In other words, the following file would parse successfully:

```beancount
2024-03-29 balance Aktiva:Bank:Giro  123.45 USD
```

Then it is the responsibility of the consumer to check the meaning of it or to raise an error.
